### ISSUE TITLE
TypeError: t.json is not a function

### ISSUE THREAD

**Issue by Julien-ELKAD** [EvgeniyMukhamedjanov/liquid-ajax-cart#107]
![Capture d'écran 2024-12-03 194106](https://github.com/user-attachments/assets/cbfe85ec-ddea-49cf-a143-7f9b9a8d5019)

Hi all,

I'm currently really stuck on a huge problem. My website's cart is completely broken due to an error of how the update.js response is handled. 

I've made a lot of tests and I've came to the conclusion that it's happening on all the v2 versions of the liquid-ajax-cart (v1 does not seem to reproduce this problem)

I've tried downloading the src files of liquid-ajax-cart so I could add console logs of the request on **line 209 of the ajax-api.ts file.** The issue seems to come from this request because the error in my console log point to that function. I therefore logs the response before the response.json() line and it only returns a number (like 805, 2656, 3589). I don't understand why suddenly this function returns numbers instead of a body that we can parse to JSON.

Do you guys have any idea on how to fix it or do you at least reproduce the same problem?

**Comment by Julien-ELKAD** [comment]
After several hours searching, I've finally managed to fix the issue. I think that Shopify changed how the update.js endpoint works. Indeed, when I make a request to update.js with the body {"sections": "section-cart-drawer"}, I received the error I mentionned above. However if you put "updates": {} inside your body, it works. I've edited the src files locally to make it work but maybe if you want me to create a PR, I would be glad to help :) 

Problem solved but still curious if I was the only one or if Shopify really changed the way the update.js endpoint works

**Comment by Julien-ELKAD** [comment]
Hey @EvgeniyMukhamedjanov ,

Thank you for your feedback !

The url of one of the website I've noticed the error is https://www.beau-domaine.com/ 
And the edits I've made are below the comments "Add the empty updates to the body" in the ajax-api.ts :

```
if (requestBody !== undefined) {
    let sectionsParam: JSONValueType = undefined;
    if (requestBody instanceof FormData || requestBody instanceof URLSearchParams) {
      if (requestBody.has('sections')) {
        sectionsParam = requestBody.get('sections').toString();
      }
    } else {
      sectionsParam = requestBody.sections;
    }
    if (typeof sectionsParam === 'string' || <JSONValueType>sectionsParam instanceof String || Array.isArray(sectionsParam)) {

      if (Array.isArray(sectionsParam)) {
        allSections.push(...(sectionsParam as string[]));
      } else {
        allSections.push(...((sectionsParam as string).split(',')));
      }

      // if it is an "add.js" request, it is better to get all the sections html from an extra request,
      // because the response of the "add.js" request might contain html generated BEFORE merging cart items
      // https://github.com/EvgeniyMukhamedjanov/liquid-ajax-cart/issues/72
      if (REQUEST_ADD === requestType) {
        extraRequestSections.push(...allSections.slice(0, 5));
      }

      // Add sections starting from index 5th to the extra request,
      // as Shopify supports maximum 5 sections per request
      if (allSections.length > 5) {
        extraRequestSections.push(...allSections.slice(5));
        const newSectionsParam = allSections.slice(0, 5).join(',');
        if (requestBody instanceof FormData || requestBody instanceof URLSearchParams) {
          requestBody.set('sections', newSectionsParam);
        } else {
          requestBody.sections = newSectionsParam;
        }
      }
    } else if (sectionsParam !== undefined && sectionsParam !== null) {
      console.error(`Liquid Ajax Cart: "sections" parameter in a Cart Ajax API request must be a string or an array. Now it is ${sectionsParam}`);
    }
    
    // Add the empty updates to the body
    if (requestType == "update" && requestBody && typeof requestBody === 'object' && !Array.isArray(requestBody) && !requestBody.hasOwnProperty('updates')) {
      (requestBody as any).updates = {};
    }
  }
  ```
  
  And 
  
  ```
  function extraRequest(sections: string[] = []): Promise<{ ok: boolean, status: number, body: JSONObjectType }> {
  const requestBody: JSONObjectType = {};
  if (sections.length > 0) {
    requestBody.sections = sections.slice(0, 5).join(',');
  }

  // Add the empty updates to the body
  if (!requestBody.updates && getEndpoint(REQUEST_UPDATE) == "/cart/update.js") {
    requestBody.updates = {};
  }

  return fetch(getEndpoint(REQUEST_UPDATE), {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(requestBody)
  }).then(response => response.json().then(responseBody => {
    const data = {
      ok: response.ok,
      status: response.status,
      body: responseBody
    };
    if (sections.length < 6) {
      return data;
    }

    return extraRequest(sections.slice(5)).then(addData => {
      if (addData.ok && addData.body?.sections && typeof addData.body.sections === 'object') {
        if (!('sections' in data.body)) {
          data.body.sections = {};
        }
        data.body.sections = {...data.body.sections, ...addData.body.sections}
      }
      return data;
    })
  }));
}
```

**Comment by EvgeniyMukhamedjanov** [comment]
@Julien-ELKAD 

I've sent a pure fetch request and it also returns a promise that gets immediately resolved with a number. Same as in your case. That makes me think you have some JavaScript code or code coming from an app that overrides the original "fetch" function and changes its logic. I have no other idea why the "fetch" function returns a promise with a number instead of promise with a response object.

<img width="986" alt="image" src="https://github.com/user-attachments/assets/d2d2e0ee-ab27-4e55-b36b-ff3b5e2c8477">

I also noticed that when you send a fetch update.js request without `updates` prop, despite it returns the promise with a number, the request is actually sent by the browser (you can see that in the Network tab). 

I didn't find the code that overrides the original "fetch" function so I'm not sure 100%.

Also I would recommend using the `liquid-ajax-cart:request-start` event to add the `updates` prop to the request instead of patching source code if you consider updating Liquid Ajax Cart version in the future in order not to lose your changes.
The way how to do that is shown here: https://liquid-ajax-cart.js.org/v2/event-request-start/#mutate-a-request :-) 
But of course it is up to you.

If you find a reason of such strange "fetch" behavior, let me know as well! Thank you!

**Comment by Julien-ELKAD** [comment]
Hey @EvgeniyMukhamedjanov ,

Thank you for your input :) 

From what I saw and informations I have, I'm not sure it's related to something we've made. I'm almost sure it's not a custom js problem because I've previewed all the previous version of the theme and the fetch response also returned a number (actually, I've made another test with v1 and it also had the same response with a number). 

I've also asked the client if they've made edits (new apps, new settings ...) and they told me they did not. So it let me with 2 possibilities : Shopify has changed the way this endpoint works only for certain store (or maybe they've made a mistake on a recent edit) or an app is now impacting the fetch due to an update (or something the client've made but does not remember)

Wish I could know ahah but I guess we will have to wait and see if any other dev have this problem

I'm going to take your suggestion in consideration right away. Indeed, it's way better to edit the request on my js than on your src files :) 

Thank you! And above all, thank you very much for your package it's a real time saver :)

**Comment by Julien-ELKAD** [comment]
Unfortunately, I have no other choices to leave one of the edit I've made to the ajax-api.ts file on the extraRequest function because whenever a add.js is sent, it then triggers the extraRequest function (which is a call to the update.js endpoint) but that is not triggering the ```liquid-ajax-cart:request-start``` so I can edit this request outside of the ajax-api.ts file (except if you have any suggestion of course :) )

**Comment by EvgeniyMukhamedjanov** [comment]
@Julien-ELKAD You are right, it is not possible to change the extra update request payload from the `request-start` event handler. I can add that additional payload `"updates": {}` to the `extraRequest` function (similar to what you did in the second code block you shared). My question is why do you need the code change in the `cartRequest` function (the one you shared in the first code block). As far as I remember Liquid Ajax Cart doesn't send any update.js requests except the one from the `extraRequest` function.

Could you check please if your store works with only the `extraRequest` code change? If so, I'll just add that fix into the lib so that you can use not patched version and could update in the future if needed.

Note: if you call the `liquidAjaxCart.update` method somewhere, then you'll need to pass the `{"updates": {}}` payload as a first parameter in case you remove the first code change you shared.

**Comment by Julien-ELKAD** [comment]
Hey @EvgeniyMukhamedjanov thank you for your feedback :) 

Indeed in the first block of code, I just added ```"updates" : {}``` in case I forgot to pass the ```"updates": {}``` whenever I make a call to ```liquidAjaxCart.update```. 

But after your reply, I did use the ```request-start``` event to handle that and remove my additionnal code in the ajax-api.ts file (I just kept the ```"updates": {}``` inside the ```extraRequest```) 

So I would be glad if you add this in the ```extraRequest``` function so I can keep liquidAjaxCart up to date :)

**Comment by EvgeniyMukhamedjanov** [comment]
Hey @Julien-ELKAD '

I've just released the new version, let me know if that works for you :-) 

Also let me know if I'm allowed to add the [beau-domaine.com/](https://www.beau-domaine.com/) to the liquid-ajax-cart home page "Showcase" section and maybe you have some other sites that are allowed to be added there.

**Comment by Julien-ELKAD** [comment]
@EvgeniyMukhamedjanov Awesome thank you! :) I've now switched back to yourpackage instead of my local version and it works like a charm

You can of course use this website to shwocase liquid-ajax-cart but we are publishing a whole new version of our cart in the next few days so if you want to way for the latest version to be published, I can let you know

**Comment by EvgeniyMukhamedjanov** [comment]
Hey @Julien-ELKAD That is a good news!

Regarding "showcase" -- yes, I'll wait for the few days :-) 

Thank you!

**Comment by Julien-ELKAD** [comment]
Hey @EvgeniyMukhamedjanov ,

Our new cart is now live (it may have some bugs at first since we changed a lot of things)

Thank you for everything
