### ISSUE TITLE
Liquid Ajax Cart: the HTML for the "ajax-cart-section" section was requested but the response is null

### ISSUE THREAD

**Issue by franjuju** [EvgeniyMukhamedjanov/liquid-ajax-cart#26]
Hi, 

First, thank you for this really useful library. I'm using it since a while on my Shopify website but when I switch from version 1.6 to 1.10.2 I face an issue. 

I've obviously read multiple times the installation guide to be sure that I've checked all the steps. However, everytime I add a product to the cart or update the cart, I have this weird error in the console 'Liquid Ajax Cart: the HTML for the "ajax-cart-section" section was requested but the response is null'. I've tried a lot of things to spot what is the problem but I can't find what is the problem.

### Here is my code from the theme.liquid
`
  {% section 'cart-drawer' %}
  <div class="cart-overlay close-cart" data-ajax-cart-toggle-class-button="js-my-cart-open"></div>
  <script type="application/json" data-ajax-cart-initial-state >
    {{ cart | json }}
  </script>
  
  <script type="module">
  import '{{ "liquid-ajax-cart-v1.10.2.js" | asset_url }}';
  </script>
`

### And my cart-drawer section
![Capture](https://user-images.githubusercontent.com/57411630/177038164-392b7bb2-af6b-4f2e-8b8a-51f9602bb373.PNG)
![Capture-2](https://user-images.githubusercontent.com/57411630/177038165-619dda80-9979-4c21-9577-9e7f7eb3608a.PNG)

**Comment by EvgeniyMukhamedjanov** [comment]
Hi, Thank you for using Liquid Ajax Cart.

You see this error because you have `id="shopify-section-ajax-cart-section"` in your code. I'm not sure why you need this id but its stucture exaclty matches the Shopify sections ids: `shopify-section-[section-name]` (you can check any section id, that is generated by shopify, it will have the same stuctured id) .

So Liquid Ajax Cart "thinks" that your manual `id="shopify-section-ajax-cart-section"` is also a Shopify section wrapper and tries to request an HTML for the "ajax-cart-section" (shopify-section-**ajax-cart-section**) section that doesn't exists.

In order to fix this issue try to avoid using manual ids that begin with "shopify-section-".

**Comment by franjuju** [comment]
Amazing! Thank you very much, this fixed my issue!
