### ISSUE TITLE
cartRequestAdd doesn't work

### ISSUE THREAD

**Issue by haroldao** [EvgeniyMukhamedjanov/liquid-ajax-cart#6]
![image](https://user-images.githubusercontent.com/36776278/148979117-7a105128-11d3-49d7-a879-942cc7763a2b.png)
![image](https://user-images.githubusercontent.com/36776278/148979268-e4ed60a4-90b9-415f-842a-facfef65aa48.png)
![image](https://user-images.githubusercontent.com/36776278/148979362-c6bc4592-eba3-49fc-9c8b-866f7d75dae0.png)

here's what I have in the console

**Comment by EvgeniyMukhamedjanov** [comment]
Hm, it is strange. All the requests from `cartRequest*` functions goes to the domain where you currently are. 
So it means you see 127.0.0.1 in your browser address bar? You run Shopify locally? :-))
Can you tell me what environment you work in ?
Really interesting how it might happen.

**Comment by haroldao** [comment]
> @haroldao Hm, it is strange. All the requests from `cartRequest*` functions go to the domain where you currently are. So it means you see 127.0.0.1 in your browser address bar? You run Shopify locally? :-)) Can you tell me what environment you work in ? Really interesting how it might happen.
> 
> P.S. Thanks for the pull request!

I say working locally... but we've the same issue on the live theme.
Here's the link : https://740od6vtzmda12np-59892367580.shopifypreview.com/products/coldstirred-set-pro

![image](https://user-images.githubusercontent.com/36776278/148999780-34e195d6-f86c-438d-b2cd-edcddbb7b64a.png)

**Comment by haroldao** [comment]
> Reference i

I say working locally... but we've the same issue on the live theme.
Here's the link : https://740od6vtzmda12np-59892367580.shopifypreview.com/products/coldstirred-set-pro
![image](https://user-images.githubusercontent.com/36776278/148999932-f7f37c27-18e9-4eb1-9e16-7ffff2f8f03c.png)

**Comment by haroldao** [comment]
I'm using Shopify CLI (latest version)

**Comment by EvgeniyMukhamedjanov** [comment]
@haroldao 
Regarding upsell button — I believe Shopify gives 404 because there is no `7524049420508` variant. Maybe you put a product number instead of variant number? `product_upsell.id`
This is what I see as a response after I clicked the Upsell button:
`{"status":404,"message":"Cart Error","description":"Cannot find variant"}`
I believe you need to try `product_upsell.first_available_variant`.

And also about the "Add to cart" button. I saw you added the `data-ajax-cart-toggle-class-button="js-my-cart-open | add"` to it. Most likely to open the cart after product is added to cart. But the product form button and the `data-ajax-cart-toggle-class-button` can't work together that is why now the "Add to cart" button doesn't do anything except opening the cart. To fix this — remove the  `data-ajax-cart-toggle-class-button` from the "add to cart" button and add the following snippet to open the cart:
```javascript
import { subscribeToCartAjaxRequests } from '{{ "liquid-ajax-cart-v1.7.0.js" | asset_url }}';

// Define a callback for all the Cart Ajax API requests
// It will be called BEFORE each request is getting performed
subscribeToCartAjaxRequests(( requestState, subscribeToResult ) => {

  // If the request is 'Add to cart'
  if ( requestState.requestType === 'add' ) {
    
    // Define a callback that will be called after the request is finished
    subscribeToResult( requestState => {

      // If the request is successful 
      if ( requestState.responseData?.ok ) {

        // Add the js-my-cart-open class
        document.body.classList.add('js-my-cart-open');
      }
    });
  }
});
```

**Comment by haroldao** [comment]
Thank you so much. You're right that's what I did. I thought it required Product.id ✅

**Comment by EvgeniyMukhamedjanov** [comment]
@haroldao You are welcome. All the `requestCart*` functions are just wrappers for Shopify API.
So if you are not sure what parameters to use for the `body` of a request, you can check here:
https://shopify.dev/api/ajax/reference/cart#post-cart-add-js

And btw I believe you can try using the `data-ajax-cart-request-button` for the upsell button instead of code:
```<a href="/cart/add?id=40873055092924&quantity=1"  data-ajax-cart-request-button="">Upsell button</a>```

**Comment by haroldao** [comment]
👍🏼

**Comment by haroldao** [comment]
> @haroldao Regarding upsell button — I believe Shopify gives 404 because there is no `7524049420508` variant. Maybe you put a product number instead of variant number? `product_upsell.id` This is what I see as a response after I clicked the Upsell button: `{"status":404,"message":"Cart Error","description":"Cannot find variant"}` I believe you need to try `product_upsell.first_available_variant`.
> 
> And also about the "Add to cart" button. I saw you added the `data-ajax-cart-toggle-class-button="js-my-cart-open | add"` to it. Most likely to open the cart after product is added to cart. But the product form button and the `data-ajax-cart-toggle-class-button` can't work together that is why now the "Add to cart" button doesn't do anything except opening the cart. To fix this — remove the `data-ajax-cart-toggle-class-button` from the "add to cart" button and add the following snippet to open the cart:
> 
> ```js
> import { subscribeToCartAjaxRequests } from '{{ "liquid-ajax-cart-v1.7.0.js" | asset_url }}';
> 
> // Define a callback for all the Cart Ajax API requests
> // It will be called BEFORE each request is getting performed
> subscribeToCartAjaxRequests(( requestState, subscribeToResult ) => {
> 
>   // If the request is 'Add to cart'
>   if ( requestState.requestType === 'add' ) {
>     
>     // Define a callback that will be called after the request is finished
>     subscribeToResult( requestState => {
> 
>       // If the request is successful 
>       if ( requestState.responseData?.ok ) {
> 
>         // Add the js-my-cart-open class
>         document.body.classList.add('js-my-cart-open');
>       }
>     });
>   }
> });
> ```

It works. Ty !! btw it's `product_upsell.first_available_variant.id` (`section.settings.product_upsell.first_available_variant.id`) not `product_upsell.first_available_variant` (`product_upsell.first_available_variant`) 🎉

**Comment by EvgeniyMukhamedjanov** [comment]
@haroldao 
Happy to help!
I saw you added the `data-ajax-cart-request-button` attribute to the upsell button. The `data-ajax-cart-request-button` requires a valid URL set. There is no URL provided that's why there is the error `Liquid Ajax Cart: a data-ajax-cart-request-button element doesn't have a valid URL` when you click on it.
So basically I advised to use  `data-ajax-cart-request-button` attribute INSTEAD of the script that you shared with me (with the `cartRequestAdd` function inside) but now you have both: the script with the `cartRequestAdd` and the  `data-ajax-cart-request-button` attribute.

My advice is if you go with the script then you should remove the  `data-ajax-cart-request-button` attribute.

Or remove the script and add a valid URL for the  `data-ajax-cart-request-button`:
`<div class="product__upsell" data-ajax-cart-request-button="/cart/add?id=42304985989340&quantity=1">`
Or you can make it a link so it will work without JS even:
`<a class="product__upsell" href="/cart/add?id=42304985989340&quantity=1" data-ajax-cart-request-button>`

**Comment by haroldao** [comment]
ty. Updated :)
