### ISSUE TITLE
Floating cart not updating on add to cart

### ISSUE THREAD

**Issue by doideaco** [EvgeniyMukhamedjanov/liquid-ajax-cart#67]
Playing with the library in a clean theme, displaying the floating cart produces inconsistent results when adding to cart.

Seems data is not updating, needs a refresh to see changes. 

Browser: Safari 16.3 Mac

**Comment by EvgeniyMukhamedjanov** [comment]
Can you share a preview link and steps to reproduce the issue?

**Comment by doideaco** [comment]
Also noticed plus/minus buttons don't function either

**Comment by EvgeniyMukhamedjanov** [comment]
This is happening because your cart isn't inside a Shopify section.
Liquid Ajax Cart uses Shopify Sections API to update the cart's content, which is available only if you put your content in a  Shopify section.
So to fix that -- create a new shopify section and make sure that the element with the `data-ajax-cart-section` attribute and all its children is inside the section.
<img width="1280" alt="image" src="https://github.com/EvgeniyMukhamedjanov/liquid-ajax-cart/assets/13817355/cb0ca73d-f6f0-4dc4-a251-9778ccdfe79e">

**Comment by doideaco** [comment]
Awesome this solves it. Thank you
